In [8]:
#cau8
import numpy as np
#DT=P.dot(N)
##Dt=p.matmul(P,N)
#luu y, muon nhan 2 ma tran thi col thang nay phai bang row thang kia
#ex (a,x)*(x,y) dung
#ex ()
P=np.array([2,1,3])
N=np.array([[12,15,10,16,12],[5,9,14,7,10],[8,12,10,9,15]])
DT=P.dot(N)
print('DT=',DT)


ModuleNotFoundError: No module named 'numpy'

In [ ]:
#cau9
import numpy as np

T=np.array([[0.6,0.7],[0.4,0.3]])
p=np.array([[0.5],[0.5]])
print('T=',T)
print('p=',p)
Tk=np.copy(T)
for k in range(1,100001):
    pk=np.matmul(Tk,p)
    Tk=np.matmul(Tk,T)
    if(k==1 or k==2 or k==10 or k==100 or k==100000):
      print('k=',k)
      print('pk=',pk)

T= [[0.6 0.7]
 [0.4 0.3]]
p= [[0.5]
 [0.5]]
k= 1
pk= [[0.65]
 [0.35]]
k= 2
pk= [[0.635]
 [0.365]]
k= 10
pk= [[0.63636364]
 [0.36363636]]
k= 100
pk= [[0.63636364]
 [0.36363636]]
k= 100000
pk= [[0.63636364]
 [0.36363636]]


In [ ]:
#cau10
import numpy as np
A=np.array([[-1,4,8],[-9,1,2]])
B=np.array([[5,8],[0,-6],[5,6]])
C=np.array([[-4,1],[6,5]])
D=np.array([[-6,3,1],[8,9,-2],[6,-1,5]])
print('A=',A)
print('B=',B)
print('C=',C)
print('D=',D)
print('a) AB^T khong ton tai')
print('b) BC^T=',np.matmul(B,C.T))
print('c)(C-C^T)=',C-C.T)
print('d)(D-D^T)=',D-D.T)
print('e) (D^T)^T=',(D.T).T)
print('f) 2C^T=',2*(C.T))
print('g) A^T+B=',A.T+B)
print('h)(A^T+B)^T=',(A.T+B).T)
print('((2A^T-5B)^T=',(2*A.T-5*B).T)
print('((-D)^T)=',(-1*D).T)
print('(-D^T)=',-1*(D.T))
print('((C^2)^T=',(C*2).T)
print('(C^T)^2=',(C.T)*(C.T))

A= [[-1  4  8]
 [-9  1  2]]
B= [[ 5  8]
 [ 0 -6]
 [ 5  6]]
C= [[-4  1]
 [ 6  5]]
D= [[-6  3  1]
 [ 8  9 -2]
 [ 6 -1  5]]
a) AB^T khong ton tai
b) BC^T= [[-12  70]
 [ -6 -30]
 [-14  60]]
c)(C-C^T)= [[ 0 -5]
 [ 5  0]]
d)(D-D^T)= [[ 0 -5 -5]
 [ 5  0 -1]
 [ 5  1  0]]
e) (D^T)^T= [[-6  3  1]
 [ 8  9 -2]
 [ 6 -1  5]]
f) 2C^T= [[-8 12]
 [ 2 10]]
g) A^T+B= [[ 4 -1]
 [ 4 -5]
 [13  8]]
h)(A^T+B)^T= [[ 4  4 13]
 [-1 -5  8]]
((2A^T-5B)^T= [[-27   8  -9]
 [-58  32 -26]]
((-D)^T)= [[ 6 -8 -6]
 [-3 -9  1]
 [-1  2 -5]]
(-D^T)= [[ 6 -8 -6]
 [-3 -9  1]
 [-1  2 -5]]
((C^2)^T= [[-8 12]
 [ 2 10]]
(C^T)^2= [[16 36]
 [ 1 25]]


In [ ]:
#cau11
A=np.array([[2,4,1],[6,7,2],[3,5,9]])
print('A=',A)
print(A.shape)
if(A.shape[0]==A.shape[1]):
    print('A la ma tran vuong')
else:
    print('A khong phai tra man vuong')

if np.allclose(A.T,A):
    print("A is symetric")
else:
    print("A is not symetric")

print('11d=',np.triu(A))
print("11e=",np.tril(A))

A= [[2 4 1]
 [6 7 2]
 [3 5 9]]
(3, 3)
A la ma tran vuong
A is not symetric
11d= [[2 4 1]
 [0 7 2]
 [0 0 9]]
11e= [[2 0 0]
 [6 7 0]
 [3 5 9]]


In [3]:
#cau12
import numpy as np
A=np.array([[6,0,0,5],[1,7,2,-5],[2,0,0,0],[8,3,1,8]])
B=np.array([[1,-2,5,2],[0,0,3,0],[2,-6,-7,5],[5,0,4,4]])
C=np.array([[3,5,-8,4],[0,-2,3,-7],[0,0,1,5],[0,0,0,2]])
D=np.array([[4,0,0,0],[7,-1,0,0],[2,6,3,0],[5,-8,3,0],[5,-8,4,-3]])
E=np.array([[4,0,-7,3,-5],[0,0,2,0,0],[7,3,-6,4,-8],[5,0,5,2,-3],[0,0,9,-1,2]])
F=np.array([[6,3,2,4,0],[9,0,-4,1,0],[8,-5,6,7,1],[3,0,0,0,0],[4,2,3,2,0]])
print('A=',np.linalg.det(A))
print('B=',np.linalg.det(B))
print('C=',np.linalg.det(C))
print('D khong phai ma tran vuong')
print('E=',np.linalg.det(E))
print('F=',np.linalg.det(F))

A= 10.000000000000007
B= -5.999999999999997
C= -12.0
D khong phai ma tran vuong
E= 5.999999999999996
F= 9.000000000000014


In [4]:
#cau15
import numpy as np
a=np.array([[2,4,5/2],[-3/4,2,1/4],[1/4,1/2,2]])
b=np.array([[1,-1/2,3/4],[3/2,1/2,-2],[1/4,1,1/2]])
#a^-1
a_inv=np.linalg.inv(a)
b_inv=np.linalg.inv(b)

print("15a.1\n",np.matmul(a_inv,b_inv))
print("15a.2\n",np.linalg.inv(np.matmul(a,b)))
print("15a.3\n",np.linalg.inv(np.matmul(b,a)))

print("15b.1\n",(a_inv).T)
print("15b.2\n",np.linalg.inv(a.T))

15a.1
 [[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]
15a.2
 [[ 0.21096296 -0.256      -0.1517037 ]
 [-0.15365079  0.20571429  0.56634921]
 [ 0.05367196 -0.28342857  0.12833862]]
15a.3
 [[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]
15b.1
 [[ 0.32804233  0.13227513 -0.07407407]
 [-0.57142857  0.28571429  0.        ]
 [-0.33862434 -0.2010582   0.59259259]]
15b.2
 [[ 0.32804233  0.13227513 -0.07407407]
 [-0.57142857  0.28571429 -0.        ]
 [-0.33862434 -0.2010582   0.59259259]]


In [5]:
#cau13

import numpy as np

def random_matrix(n):
    return np.random.rand(n, n)

#chaythumatran5x5
A = random_matrix(5)
B = random_matrix(5)
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_A_plus_B = np.linalg.det(A + B)

print("chaythumatran5x5")
print("det(A + B) - det(A) - det(B) = ", det_A_plus_B - det_A - det_B)
print("Is det(A + B) = det(A) + det(B)?", np.allclose(det_A_plus_B, det_A + det_B))

#chaythumatran3x3
A = random_matrix(3)
B = random_matrix(3)
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_A_plus_B = np.linalg.det(A + B)

print("chaythumatran3x3")
print("det(A + B) - det(A) - det(B) = ", det_A_plus_B - det_A - det_B)
print("Is det(A + B) = det(A) + det(B)?", np.allclose(det_A_plus_B, det_A + det_B))

#chaythumatran4xx4
A = random_matrix(4)
B = random_matrix(4)
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_A_plus_B = np.linalg.det(A + B)

print("chaythumatran4xx4")
print("det(A + B) - det(A) - det(B) = ", det_A_plus_B - det_A - det_B)
print("Is det(A + B) = det(A) + det(B)?", np.allclose(det_A_plus_B, det_A + det_B))

#chaythumatran2xx2
A = random_matrix(2)
B = random_matrix(2)
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_A_plus_B = np.linalg.det(A + B)

print("chaythumatran2xx2")
print("det(A + B) - det(A) - det(B) = ", det_A_plus_B - det_A - det_B)
print("Is det(A + B) = det(A) + det(B)?", np.allclose(det_A_plus_B, det_A + det_B))

chaythumatran5x5
det(A + B) - det(A) - det(B) =  0.491315083632164
Is det(A + B) = det(A) + det(B)? False
chaythumatran3x3
det(A + B) - det(A) - det(B) =  -0.5288075981119492
Is det(A + B) = det(A) + det(B)? False
chaythumatran4xx4
det(A + B) - det(A) - det(B) =  -0.4929723917147831
Is det(A + B) = det(A) + det(B)? False
chaythumatran2xx2
det(A + B) - det(A) - det(B) =  0.9241446553543146
Is det(A + B) = det(A) + det(B)? False


In [6]:
#cau14

import numpy as np

def random_matrix(n):
    return np.random.rand(n, n)

#chaythumatran2xx2
A = random_matrix(2)
B = random_matrix(2)
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_AB = np.linalg.det(A.dot(B))

print("chaythumatran2xx2")
print("det(AB) - det(A) * det(B) = ", det_AB - det_A * det_B)
print("Is det(AB) = det(A) * det(B)?", np.allclose(det_AB, det_A * det_B))

#chaythumatran3x3
A = random_matrix(3)
B = random_matrix(3)
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_AB = np.linalg.det(A.dot(B))

print("chaythumatran3x3")
print("det(AB) - det(A) * det(B) = ", det_AB - det_A * det_B)
print("Is det(AB) = det(A) * det(B)?", np.allclose(det_AB, det_A * det_B))

# chaythumatran44
A = random_matrix(4)
B = random_matrix(4)
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_AB = np.linalg.det(A.dot(B))

print("chaythumatran4xx4")
print("det(AB) - det(A) * det(B) = ", det_AB - det_A * det_B)
print("Is det(AB) = det(A) * det(B)?", np.allclose(det_AB, det_A * det_B))

#chaythumatran5xx5
A = random_matrix(5)
B = random_matrix(5)
det_A = np.linalg.det(A)
det_B = np.linalg.det(B)
det_AB = np.linalg.det(A.dot(B))

print("chaythumatran5xx5")
print("det(AB) - det(A) * det(B) = ", det_AB - det_A * det_B)
print("Is det(AB) = det(A) * det(B)?", np.allclose(det_AB, det_A * det_B))


chaythumatran2xx2
det(AB) - det(A) * det(B) =  -2.949029909160572e-17
Is det(AB) = det(A) * det(B)? True
chaythumatran3x3
det(AB) - det(A) * det(B) =  8.326672684688674e-17
Is det(AB) = det(A) * det(B)? True
chaythumatran4xx4
det(AB) - det(A) * det(B) =  1.734723475976807e-18
Is det(AB) = det(A) * det(B)? True
chaythumatran5xx5
det(AB) - det(A) * det(B) =  4.020865400616164e-18
Is det(AB) = det(A) * det(B)? True
