In [ ]:
#cau1
x=[1,3,5,2,9]
print(x)
y=[-1,3,15,27,29]
print(y)
print(len(x))
import numpy as np
vx=np.array(x)
vy=np.array(y)
vz=vx+vy
print(vx)
print(vy)
print("vx+vy=",vz)
print("vx*vy=",vx*vy)
print("x[0]=",x[0])
print("vx[1]=",vx[1])
print("vx[2]",vx[2])

[1, 3, 5, 2, 9]
[-1, 3, 15, 27, 29]
5
[1 3 5 2 9]
[-1  3 15 27 29]
vx+vy= [ 0  6 20 29 38]
vx*vy= [ -1   9  75  54 261]
x[0]= 1
vx[1]= 3
vx[2] 5


In [23]:
#cau2
#a
import numpy as np
import math
n=int(input("nhap so tu nhien n duong:"))
b=[]
for i in np.arange(0,n):
  b.append(12+i*2)
print("cau a: b=",b)
#b
c=[]
for i in np.arange(0,n):
  c.append(31+i*2)
print("cau b: c=",c)
#c
x= []
for i in range (0,2*n+1):
  x.append(i-n)
print("cau c x= ",x)
#d
d = []
for i in range (0,2*n+1):
  d.append(n-i)
print("cau d y= ",d)
#e
e=[]
for i in np.arange(-n/2-4,n/2):
  if(i%2==0):
       e.append(-int(i))
print("cau e: z=",e)
#f
f=[]
for i in np.arange(0,n):
  if(i%2==0):
      if(i==0):
          f.append(1)
      else:
          f.append(1/int(i))
print("cau f: w=",f)
#g
fibo=[1,1]
g=[]
for i in np.arange(2,n):
  fibo.append(fibo[i-2]+fibo[i-1])
print(fibo)
for i in np.arange(0,n):
    g.append(1/fibo[i])
print("cau g: d=",g)
#h
h = []
count = 0
num = 2
while(count<n):
    for i in np.arange(2, num+1):
        if num == 2:
            h.append(1/num)
            num = num + 1
            count = count + 1
            continue
        if num % i == 0 and num != i :
            num = num + 1
            continue
    h.append(1/num)
    num = num + 1
    count = count + 1
print("cau h: e=",h)
#i
i1 = []
i1.append(1)
sum = 1
for i in np.arange(1, n+1):
    sum = sum + (i+1)
    i1.append(sum)
print("a = ", i1)
#jj
j1=[]
for i in np.arange(1,n):
  j1.append(1/(i**2+1))
print("n=",j1)
#k
p = []
num1 = 0
num2 = 1
for i in np.arange(n):
    p.append((num1+i)/(num2+i))
print("p = ", p)
#caul
#ord()
#chr()
char=[]
for i in np.arange(ord('a'),ord('z')+1):
  char.append(chr(i))
print('char=',char)
#caum
CHAR=[]
for i in np.arange(ord('A'),ord('Z')+1):
  CHAR.append(chr(i))
print('char=',CHAR)


nhap so tu nhien n duong:10
cau a: b= [12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
cau b: c= [31, 33, 35, 37, 39, 41, 43, 45, 47, 49]
cau c x=  [-10, -9, -8, -7, -6, -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
cau d y=  [10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, -1, -2, -3, -4, -5, -6, -7, -8, -9, -10]
cau e: z= [8, 6, 4, 2, 0, -2, -4]
cau f: w= [1, 0.5, 0.25, 0.16666666666666666, 0.125]
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
cau g: d= [1.0, 1.0, 0.5, 0.3333333333333333, 0.2, 0.125, 0.07692307692307693, 0.047619047619047616, 0.029411764705882353, 0.01818181818181818]
cau h: e= [0.5, 0.3333333333333333, 0.2, 0.14285714285714285, 0.09090909090909091, 0.07692307692307693, 0.058823529411764705, 0.05263157894736842, 0.043478260869565216, 0.037037037037037035]
a =  [1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 66]
n= [0.5, 0.2, 0.1, 0.058823529411764705, 0.038461538461538464, 0.02702702702702703, 0.02, 0.015384615384615385, 0.012195121951219513]
p =  [0.0, 0.5, 0.6666666666666666, 0.75, 0.8, 0.83333333333

In [8]:
#ca3
import numpy as np 
x=[]

n=int(input("nhap so tu nhien n duong:"))
x=np.logspace(1,n,num = n, base =10)
print(x)

nhap so tu nhien n duong:3
[  10.  100. 1000.]


In [7]:
#cau4
import numpy as np
x=[1,2,3]
y=[98,12,33]
vx=np.array(x)
vy=np.array(y)
print(vx) 
print(vy)
vz=np.array(x+y)
print("vecto z=",vz)


[1 2 3]
[98 12 33]
vecto z= [ 1  2  3 98 12 33]


In [ ]:
#cau6
#vx=np.arange(0,22,2)
x=[0,2,4,6,8,10,12,14,16,18,20]
vx=np.array(x)
print('x=',vx)
print('cau a',vx[:6])
print('cau b',vx[-3:len(vx)])
print('cau c',vx[[0,3,len(vx)-1]])
print('cau d',vx[[0,2,4,6]])
print('cau e',vx[1:len(vx)-1:2]) 
print('cau f',vx[0:len(vx)-1:2]) 



x= [ 0  2  4  6  8 10 12 14 16 18 20]
cau a [ 0  2  4  6  8 10]
cau b [16 18 20]
cau c [ 0  6 20]
cau d [ 0  4  8 12]
cau e [ 2  6 10 14 18]
cau f [ 0  4  8 12 16]


In [16]:
#cau7
import numpy as np
x=[3,11,-9,-131,-1,1,-11,91,-6,407,-12,-11,12,153,371]
vx=np.array(x)
print('x=',vx)
print('a) max=',np.max(vx))
print('b) min=',np.min(vx))
print('c)',np.where(vx>10))
print('d)',np.flipud(vx))
print('e)',np.sort(vx))
print('f)',-np.sort(-vx))
from collections import Counter
x=[3,11,-9,-131,-1,1,-11,91,-6,407,-12,-11,12,153,371]
counts=dict(Counter(x))
duplicates={key:value for key,value in counts.items() if value >1}
print(duplicates)


x= [   3   11   -9 -131   -1    1  -11   91   -6  407  -12  -11   12  153
  371]
a) max= 407
b) min= -131
c) (array([ 1,  7,  9, 12, 13, 14]),)
d) [ 371  153   12  -11  -12  407   -6   91  -11    1   -1 -131   -9   11
    3]
e) [-131  -12  -11  -11   -9   -6   -1    1    3   11   12   91  153  371
  407]
f) [ 407  371  153   91   12   11    3    1   -1   -6   -9  -11  -11  -12
 -131]
{-11: 2}
