In [4]:
#cau1
#a
import numpy as np
cau1=np.array([[1,-7],[-2,-3]])
norm=np.linalg.norm(cau1,1)
print("A1:",norm)
#b
import numpy as np
cau1=np.array([[2,-8],[3,1]])
norm=np.linalg.norm(cau1,1)
print("A3:",norm)
#c
import numpy as np
cau1=np.array([[-2,8],[3,1]])
norm=np.linalg.norm(cau1,1)
print("A2:",norm)
#d
import numpy as np
cau1=np.array([[2,3],[1,-1]])
norm=np.linalg.norm(cau1,1)
print("A4:",norm)
#e
import numpy as np
cau1=np.array([[5,-4,2],[-1,2,3],[-2,1,0]])
norm=np.linalg.norm(cau1,1)
print("A5",norm)

A1: 10.0
A3: 9.0
A2: 9.0
A4: 4.0
A5 8.0


In [7]:
#cau2
#a
arrA=np.array([[1,-7],[-2,3]])
B1=np.linalg.norm(arrA,np.inf)
print("infinity norm of B1:",B1)
#b
arrA=np.array([[3,6],[1,0]])
B2=np.linalg.norm(arrA,np.inf)
print("infinity norm of B2:",B2)
#c
arrA=np.array([[5,-4,2],[-1,2,3],[-2,1,0]])
B3=np.linalg.norm(arrA,np.inf)
print("infinity norm of B3:",B3)
#d
arrA=np.array([[3,6,-1],[3,1,0],[2,4,-7]])
B4=np.linalg.norm(arrA,np.inf)
print("infinity norm of B4:",B4)
#e
arrA=np.array([[-3,0,0],[0,4,0],[0,0,2]])
B5=np.linalg.norm(arrA,np.inf)
print("infinity norm of B5:",B5)

infinity norm of B1: 8.0
infinity norm of B2: 9.0
infinity norm of B3: 11.0
infinity norm of B4: 13.0
infinity norm of B5: 4.0


In [9]:
#cau3
import numpy as np
#a
arrA=np.array([[5,-4,2],[-1,2,3],[-2,1,0]])
norm=np.linalg.norm(arrA)
print("norm C1:",norm)
Frobenius_norm=np.linalg.norm(arrA,'fro')
print("Frobenius_norm of C1:",Frobenius_norm)
#b
arrA=np.array([[1,7,3],[4,-2,2],[-2,-1,1]])
norm=np.linalg.norm(arrA)
print("norm C2:",norm)
Frobenius_norm=np.linalg.norm(arrA,'fro')
print("Frobenius_norm of C2:",Frobenius_norm)
#c
arrA=np.array([[2,3],[1,-1]])
norm=np.linalg.norm(arrA)
print("norm C3:",norm)
Frobenius_norm=np.linalg.norm(arrA,'fro')
print("Frobenius_norm of C3:",Frobenius_norm)



norm C1: 8.0
Frobenius_norm of C1: 8.0
norm C2: 9.433981132056603
Frobenius_norm of C2: 9.433981132056603
norm C3: 3.872983346207417
Frobenius_norm of C3: 3.872983346207417


In [27]:
#cau4
import numpy as np
#a
u=np.array([1,1])
v=np.array([0,1])
normu=np.linalg.norm(u)
normv=np.linalg.norm(v)
print("a. the angle between u and v:", round(np.degrees(np.arccos(np.dot(u,v)/(normu*normv))),5) )
#b
u=np.array([1,0])
v=np.array([0,1])
normu=np.linalg.norm(u)
normv=np.linalg.norm(v)
print("b. the angle between u and v:", round(np.degrees(np.arccos(np.dot(u,v)/(normu*normv))),5) )
#c
u=np.array([-2,3])
v=np.array([1/2,-1/2])
normu=np.linalg.norm(u)
normv=np.linalg.norm(v)
print("c. the angle between u and v:", round(np.degrees(np.arccos(np.dot(u,v)/(normu*normv))),5) )

a. the angle between u and v: 45.0
b. the angle between u and v: 90.0
c. the angle between u and v: 168.69007


In [35]:
#cau5
#a
u=np.array([2,3])
normu=np.linalg.norm(u)
print("A. norm: ",normu)
Unitvecto=u/normu
print("A. Unit vecto u: ",Unitvecto)
print()
#b
u=np.array([1,2,3])
normu=np.linalg.norm(u)
print("B. norm: ",normu)
Unitvecto=u/normu
print("B. Unit vecto u: ",Unitvecto)
print()
#c
u=np.array([1/2,-1/2,1/4])
normu=np.linalg.norm(u)
print("C. norm: ",normu)
Unitvecto=u/normu
print("C. Unit vecto u: ",Unitvecto)
print()
#d
u=np.array([2**(1/2),2,-(2**(1/2)),2**(1/2)])
normu=np.linalg.norm(u)
print("D. norm: ",normu)
Unitvecto=u/normu
print("D. Unit vecto u: ",Unitvecto)
print()


A. norm:  3.605551275463989
A. Unit vecto u:  [0.5547002  0.83205029]

B. norm:  3.7416573867739413
B. Unit vecto u:  [0.26726124 0.53452248 0.80178373]

C. norm:  0.75
C. Unit vecto u:  [ 0.66666667 -0.66666667  0.33333333]

D. norm:  3.1622776601683795
D. Unit vecto u:  [ 0.4472136   0.63245553 -0.4472136   0.4472136 ]



In [47]:
#cau6
import numpy as np
v1=np.array([1,2,3])
s2=np.array([7,4,3])
s3=np.array([2,1,9])
eucli= np.sqrt(np.dot((v1-s2).T,v1-s2 ))
print("Euclidean distances v1-s2 :",eucli)

eucli= np.sqrt(np.dot((v1-s3).T,v1-s3 ))
print("Euclidean distances v1-s3 :",eucli)

eucli= np.sqrt(np.dot((s2-s3).T,s2-s3 ))
print("Euclidean distances s2-s3 :",eucli)

Euclidean distances v1-s2 : 6.324555320336759
Euclidean distances v1-s3 : 6.164414002968976
Euclidean distances s2-s3 : 8.366600265340756


In [113]:
#cau7
import numpy as np
mess=""
A=np.array([[1,2,3],[2,1,2],[3,2,4]])
E=np.array([[80,98,99,85,106,94],[71,92,76,95,100,92],[124,163,140,160,176,161]])
A1=np.linalg.inv(A)
print("A^-1=",A1)
print()
D=np.matmul(A1,E)
print("Matrix D=",D)
alphabet=['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I' ,'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z','']
alphavalues = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13, 14, 15, 16, 17, 18, 19, 20, 21, 22,23, 24, 25, 26, 27,28]
D1=D-3
D1=np.round(D1,2)
print("D1=" ,D1)
for j in range(0,D1.shape[1]):
  for i in range(0,D1.shape[0]):
      for k in range(0,27):
        if(alphavalues[k]==D1[i][j]):
           mess=mess+alphabet[k]
print(mess)

A^-1= [[ 0.  2. -1.]
 [ 2.  5. -4.]
 [-1. -4.  3.]]

Matrix D= [[18. 21. 12. 30. 24. 23.]
 [19.  4. 18.  5.  8.  4.]
 [ 8. 23. 17. 15. 22. 21.]]
D1= [[15. 18.  9. 27. 21. 20.]
 [16.  1. 15.  2.  5.  1.]
 [ 5. 20. 14. 12. 19. 18.]]
OPERATIONBLUESTAR


In [ ]:
#cau8
import numpy as np
